### ISSUE TITLE
get_test_case_id_from_tags(tags) Stops at first test_case_id= in list

### ISSUE THREAD

**Issue by sjrawlins** [ATEME/robotframework-testrail#4]
Thanks for a great python utility!   If a test has multiple test-case ids, such as:

`[Tags]    xx  aa   bb   test_case_id=C750000    test_case_id=C650000    test_case_id=C634002  yy`

we should iterate thru the list and not stop at the first one.

Currently, the code stops at the first `test_case_id` tag which, as a further complication, is the first as supplied in the Robot output.xml list - not the same as the first such tag in the source code.  In the example above, the current code would only apply to test case C634002 because it gets re-arranged first.

**Comment by mnajibb** [comment]
Hi @sjrawlins , please correct me if im wrong, but in my case, when i try to execute my robot with : 
`[Tags]  test_case_id=C34579   test_case_id=C34580`

my code runs fine and output.xml showed up, but the output.xml don't mention my second tags `test_case_id=C34580`  either

my concern is, i can't implemented your pull request because my xml output is not mentioning my second tag, did you know what can i do to make it showed up in xml output?

sorry if this is out of your topic issue but i do really appreciate if you or anyone reply my concern.

Cheers
Regards,
Muhammad Najib

**Comment by sjrawlins** [comment]
Hi Muhammad,
It was hard to find you and your comment on github.  Strange that it does
not appear for me in my github inbox.  Maybe you already solved or deleted
your comment from github?  Anyway, it took me some time to realize that you
were asking me a question about RF and that you are not part of the
original authors organization (ATEME).

I believe you need TWO SPACES between your test cases, like this:

[Tags]  test_case_id=C34579   test_case_id=C34580

RF is terrible that way: it needs two spaces or more as delimiter.

I am glad to hear from you and that you are interested.  On my team, we
have come to the realization that we really should NOT have more than one
test-case per test keyword.  So we are slowly undoing that.

The philosophical problem is this:
Having a test which both PASSes and FAILs is strange and hard to reckon
with, hard to explain.

But my fix, nonetheless, will apply if you have more than one such
test_case_id tag.



Tags are simply a means of identifying tests in Robot Framework.  There is
no knowledge of "test case" behind it; it is simply a list of tags.

[Tags]    Smoke    Cnnnnnn

you can pick and choose, and the reports nicely categorize by Tags

But that's Robot.   In terms of a body of test cases, it can cause trouble
if one "keyword" (one RF test) corresponds to more than one TC in TestRail,
because you can have (and we did have)  TCs which both PASS and FAIL,
depending upon what they were bundled with


It might be easier for us to exchange personal email addresses, if you
wish.  This is my personal email.  I work for Zebra Technologies, so you
can use that email if you prefer  srawlins@zebra.com

Best Wishes,
Steve

**Comment by nsaadi** [comment]
Issue fixed by commit : 
https://github.com/ATEME/robotframework-testrail/commit/6915106f9b8e0c1ea1f08118d42bfe8a627522b9
Thx to Steve Rawlins
